{% set name = "bioregistry" %}
{% set version = "0.10.105" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bioregistry-{{ version }}.tar.gz
  sha256: 28c5aa2452ed985094d18a229cdad82b2d2f2a48e575a25abe04d27f4f4818c0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  entry_points:
    - bioregistry = bioregistry.cli:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - tqdm
    - pystow >=0.1.13
    - click
    - more-click >=0.1.2
    - pydantic
    - curies >=0.7.0

test:
  imports:
    - bioregistry
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/biopragmatics/bioregistry
  summary: Integrated registry of biological databases and nomenclatures
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - dillonroach
